/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeExample */

#ifndef _Included_NativeExample
#define _Included_NativeExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeExample
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeExample_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     NativeExample
 * Method:    getMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_NativeExample_getMessage
  (JNIEnv *, jobject);

/*
 * Class:     NativeExample
 * Method:    messageLength
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_NativeExample_messageLength
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
